### PR TITLE
feature(plugins): Add NSFW plugin.

### PR DESCRIPTION
**Pull request by jirwin**
This new plugin lets users flag content as NSFW. In order to make this effective I needed to add support for controlling whether or not links and media are automatically unfurled.

screen shot 2016-04-29 at 8 54 35 am

### CODE REVIEW

**Comment by danielsamuels** [comment]
LGTM, are you able to squash your commits down into a single commit for me?

**Comment by jirwin** [comment]
Github actually lets you do this when you merge now 😄 but sure

**Comment by danielsamuels** [comment]
I thought that too, but I'm only seeing a merge button (I checked the repo settings, and everything's set properly).

**Comment by jirwin** [comment]
@danielsamuels there you go

**Comment by danielsamuels** [comment]
Ah.. the option appears when I click 'merge'. Sorry for the trouble! Thank you so much for the PR!

**Comment by jirwin** [comment]
Thanks for the fast merge. Also thanks for the great project!

**Comment by danielsamuels** [comment]
No problem at all, I've just pushed the code live to the server too, so you should be able to use it straight-away.  Would you be interested in writing a short documentation page for it too?

**Comment by jirwin** [comment]
Sure. I'll get on that.

**Pull request merged**
